services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: collabdraw
      POSTGRES_USER: collabdraw_user
      POSTGRES_PASSWORD: collabdraw_password
    ports:
      - "5432:5432"
    volumes:
      - collabdraw_volume:/var/lib/postgresql/data
    networks:
      - collabdraw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U collabdraw_user -d collabdraw"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - collabdraw-network

  db-migrate:
    image: suhaskanwar/collabdraw-db-migrate:1
    environment:
      - DATABASE_URL=postgresql://collabdraw_user:collabdraw_password@postgres:5432/collabdraw
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - collabdraw-network
    restart: "no"

  http-backend:
    image: suhaskanwar/collabdraw-http:998d606f04cd213b0728127c0c704764bdf6ba67
    environment:
      - HTTP_SERVER_PORT=9090
      - DATABASE_URL=postgresql://collabdraw_user:collabdraw_password@postgres:5432/collabdraw
      - JWT_SECRET=secret
    ports:
      - "9090:9090"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    networks:
      - collabdraw-network

  ws-backend:
    image: suhaskanwar/collabdraw-ws:998d606f04cd213b0728127c0c704764bdf6ba67
    environment:
      - WS_SERVER_PORT=8080
      - DATABASE_URL=postgresql://collabdraw_user:collabdraw_password@postgres:5432/collabdraw
      - JWT_SECRET=secret
    ports:
      - "8080:8080"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    networks:
      - collabdraw-network

  frontend:
    image: suhaskanwar/collabdraw-frontend:998d606f04cd213b0728127c0c704764bdf6ba67
    environment:
      - NEXT_PUBLIC_HTTP_BACKEND_URL=http://http-backend:9090
      - NEXT_PUBLIC_WS_BACKEND_BASE_URL=http://ws-backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - http-backend
      - ws-backend
    networks:
      - collabdraw-network

volumes:
  collabdraw_volume:

networks:
  collabdraw-network:
    driver: bridge