FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml ./
COPY ./turbo.json ./
COPY ./apps/http-backend ./apps/http-backend

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm run db:generate

EXPOSE 9090

CMD ["pnpm", "run", "start:http"]