FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml ./
COPY ./turbo.json ./

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile
RUN pnpm run db:generate
RUN pnpm run build:packages
RUN pnpm run build:http

EXPOSE 9090

CMD ["pnpm", "run", "start:http"]