FROM node:22-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml ./
COPY ./turbo.json ./

COPY ./apps/collabdraw-frontend ./apps/collabdraw-frontend

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

RUN pnpm run build:frontend

EXPOSE 3000

CMD ["pnpm", "run", "start:frontend"]