import {
    Palette,
    Home,
    Brush,
    Camera,
    Coffee,
    Gamepad2,
    Heart,
    Music,
    Star,
    Zap,
    Book,
    Code,
    Image,
    Map,
    Pen,
    Settings,
    Shield,
    Target,
    Briefcase,
} from "lucide-react";

export const iconMap: { [key: string]: any } = {
    palette: Palette,
    brush: Brush,
    camera: Camera,
    coffee: Coffee,
    gamepad2: Gamepad2,
    heart: Heart,
    music: Music,
    star: Star,
    zap: Zap,
    book: Book,
    code: Code,
    image: Image,
    map: Map,
    pen: Pen,
    settings: Settings,
    shield: Shield,
    target: Target,
    home: Home,
    briefcase: Briefcase,
};

export const iconOptions = [
    { value: "home", label: "Home", icon: Home },
    { value: "briefcase", label: "Work", icon: Briefcase },
    { value: "coffee", label: "Coffee", icon: Coffee },
    { value: "gamepad2", label: "Gaming", icon: Gamepad2 },
    { value: "heart", label: "Personal", icon: Heart },
    { value: "star", label: "Important", icon: Star },
    { value: "brush", label: "Creative", icon: Brush },
    { value: "code", label: "Development", icon: Code },
    { value: "book", label: "Education", icon: Book },
    { value: "music", label: "Music", icon: Music },
    { value: "camera", label: "Photography", icon: Camera },
    { value: "settings", label: "Settings", icon: Settings },
];