apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
spec:
  encryptedData:
    JWT_SECRET: AgB1z6vCXfnpc/9uCNoUVvyvpwqZElB0wpEqAq49trljDHLwBu0yFFBIifOWCS+YQwM8xBJghlj2f/FnNLqbnwmmhgVtGTw/9j8OXhM4SUWZ8GiwPehFiioAam/9fccL0wLKzXamEQxPrA2vSyit0P8qWglRdai3etVwsEmqPwiWosfgNZ+2m6OlZkGywVWjJNWMknLSw3UKeMda4rSAtRBnEclrA/t1tT1zGtzTzPVZzhavTXmmQbZYhqScBN4xxj/KgqCfBBDI6iVG1d1EF6nYm2fxitaOLKrkOUK7SnOOqUER90NH4QdIxmap7fWtuApKMP+Qeu87tXMxONdtWBBsQGe1lI/HGPSSovIZjgnFuMDtj6VCGWb0VCPSmFkL6osVKIRECuBWaFSnogl6P3+56YH+xTrP7CMRlkWnJ5NCZewA5WNS1pifh7Qjqbir3tOGPcuf+fcXj2rpgv9oBAr89EdfgIhQbXwh7Oce7XcjYjwl5raF5vVXJTdpNCFu0iGJzj7QqGbmJ+E22Jzoa/Y7lp1KnTTIyhTWV+bZ5QPWTH2EqfrHsAGSxeqJPgV5/SsQuSwRpDsi2hIyNObiTM6ioQjU7OaYk4ejoyBRkm1eQotN5QAEWL3g5GguivPzK7waJgpgkburkmwgaRAMI2J3SUnkgtCOHyhxN3DdJPurPzL7LIXHjAJHvy5dwy2Gv4d+VSOcDDM=
    DATABASE_URL: AgBLXBQFKsaIIFjvFPr9eoLCvjC8bW94jTvRoZvvThGbSuK8bc3em5TDdKfS4bLDnYYyA9AIwOR3ObcOihV+DtJGWOiDCcO2nSs1UsTxON/KeV6Kr6Gj8K06GKfPSMYVKbyZcFmwD6613pboXUlmafHsPIm6iiiq7i0utDr5XEmOGmvinnIVqgCI1QhCzwf688tmLc6d1IGNfSuTfUjlLXERrIqiiwwinv1NjUjw+1pORiK7Q1lhIUURBIfhptaN/XScF8AF55TjxyHcygouavK84xF8ePjJBnRZZa9+O1agw0Ceta17Z5QCl/3gRnLJQbtWgLcJ+8QKab4KQpkBOD0ex787brdf7B57gT4efGQowOsGF5zcNXQodHswmwXNgV7U+iO1ffRa8DWiWYhUClSZXHnHUxCKfpK4v4+FKFahe6uEDV+WkItjgRRhwKlKws1x4QmKY2PpgxAoP6Gqg/fXfA4dIrFqTRhngNbZg6a/9KxLK/C2lLMmrcNeDAyu/TG+zeeK/rEBsv2QVuac+WBd/4ANr/8W9UhC2Ly42auxv3/VIQQLVNGvDywBHQaqoNoGNUZrIVaOuXRnwqkDv2ZZtq3tiuX+nZRYHOxFilgz4W/WI/qWykTXb6mzt2a/mBKL9j+PgNQKYZ+edLXYiZ6yQHqMI2zpTrVH8DvcXqzUKBxihApu/Xu6lw1K+1mJDDWKa+XbTuobnJ2CblXKZE5XIv4Fnnm3yOE+u2WgFumy9b62T9fN4286F5ZIGLywRCbtGScVc9WWR/XZ8zyFzYWJZO5vpLUSV2UCMQxLjG29kjnu3EiVzy9+Qim4fL80Dgfa7fOPWMBucRY4F0Xn5XpVINDcFEEpE9FhGPGy/nr01V5GzA==
  template:
    metadata:
      name: app-secrets

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  HTTP_SERVER_PORT: "9090"
  WS_SERVER_PORT: "8080"